feat: 추천 정책 조회 구현
INDIE-RO/INDIE-RO pull request #169
Opened 2024-06-30 08:38 UTC by hae-on

## Issue

- close #165 

## ✨ 구현한 기능

추천 정책과 관련한 로직을 만들고, ui 구현하였습니다.

https://github.com/INDIE-RO/INDIE-RO/assets/80464961/1c6d1bbb-b45a-4b8e-b4af-45a609d6bf2c

이게 1번 배너일 때랑 2번 배너일 때랑 글자 위치랑 색상이 달라서 코드가 좀 더러워졌어요...ㅠ
다행히 이미지 자체는 크기 변경이랑 상관없이 안 깨져서 그냥 하나의 이미지 사이즈로 올려놨습니다!

원래 화살표 버튼 있고, 누르면 양 옆으로 이동하게 만드려고 했는데 생각보다 붙였을 때 예쁘지가 않고 (그리고 클로버를 가려요....)
또, 1번 배너 2번 배너면 아이콘 색상 다르게 먹여야해서 일단 안 붙이고 올립니다!
배너 넘어가는 속도 괜찮은지 봐주세요~~

요건 큰 사이즈 화면일 때!

https://github.com/INDIE-RO/INDIE-RO/assets/80464961/a46cb345-b9ab-43be-b822-ba80312fb92a

## 📢 논의하고 싶은 내용
<img width="383" alt="스크린샷 2024-06-30 오후 5 32 40" src="https://github.com/INDIE-RO/INDIE-RO/assets/80464961/c72144fd-9fef-44be-b7ca-06b93d8d02a1">

얘도 결국 경고 뜨네요,,,
이거 앞에 달러 싸인 붙일까요...???

## 🎸 기타

x

2024-06-30 11:00 UTC, HyeryongChoi requested changes
캐러셀 금방 구현하셨군요 고생하셨습니다👍👍👍

코멘트 몇개 남겼는데 확인해주세요~~!!

2024-07-01 04:09 UTC, hae-on commented on Frontend/src/components/Policy/RecommendPolicy/RecommendPolicy.api.ts
> +  recommendedPolicies: RecommendPolicy[];
api에 따라 recommended로 수정하였습니다!

2024-07-01 04:10 UTC, hae-on commented on Frontend/src/components/@common/Carousel/Carousel.tsx
> +    setCurrentIndex(prevIndex => prevIndex + 1);
요거는 방금 얘기했던 것처럼 가짜 마지막 배너일 때, 갈아 끼우는 로직이 있어야 하기 때문에 그대로 가도록 하겠습니다!

2024-07-01 04:20 UTC, HyeryongChoi approved these changes

2024-07-01 04:21 UTC, merged