feat: TabMenu 구현
INDIE-RO/INDIE-RO pull request #41
Opened 2024-06-06 12:57 UTC by hae-on

## Issue

- close #40

## ✨ 구현한 기능

<img width="385" alt="스크린샷 2024-06-06 오후 9 55 21" src="https://github.com/INDIE-RO/INDIE-RO/assets/80464961/dae916f5-75de-4f33-8ad8-70775944aee7">

탭 메뉴를 구현하였습니다.
탭은 현재 다른 곳에서 재사용은 안 할 거 같아서, 그냥 TAB_MENUS로 상수화해서 이름 넣어줬어용

첵스 말대로 tab에서만 사용될 type이랑 custom hook은 해당 폴더 안에 넣습니다!
그리고 타입이 좀좀따리 안 맞아서 결국 as 쓰고 말았슴니다 하하 ㅠ
해결 방법을 아신다면,,,,알려줘요오오,,,,

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

2024-06-06 13:33 UTC, HyeryongChoi requested changes

2024-06-06 13:33 UTC, HyeryongChoi commented on Frontend/src/components/@common/TabMenu/TabMenu.tsx
> +const TAB_MENUS: Tab<CategoryVariant>[] = [
정책 상세에도 탭이 쓰여서 탭 이름들은 props로 받으면 더 좋을 것 같아요👍
그리고 정책 상세에서는 탭 이름들을 api로 받아와서 상수화도 안해줘도 되겠네용!
-> 근데 이러면 타입 안맞아서 에러나려나..

둘다 상수화하거나 둘다 api로 받아와야할까요?

2024-06-06 13:40 UTC, HyeryongChoi commented on Frontend/src/components/@common/TabMenu/TabMenu.tsx
> +    handleTabMenuSelect(event.currentTarget.value as CategoryVariant);
`as`는 고치려면 시간이 좀 걸릴 것 같으니 개발 완료 후 리팩터링 시간에 해결해보죵

2024-06-06 13:43 UTC, hae-on commented on Frontend/src/components/@common/TabMenu/TabMenu.tsx
> +const TAB_MENUS: Tab<CategoryVariant>[] = [
와 맞다.... 저 값도 api로 받는다는 거 깜빡했어요....
그럼 일단 tab 이름은 상수로 받는걸로 수정해놓겠습니다!

2024-06-06 13:44 UTC, hae-on commented on Frontend/src/components/@common/TabMenu/TabMenu.tsx
> +  const handleTabMenuClick: MouseEventHandler<HTMLButtonElement> = event => {
요거는 왜 저렇게 했냐면 event 안에 넣으니까 타입이 터졌어요 ㅎㅎㅎㅎㅎ
고친다고 해놓고 까먹고 올렸네용...
이거 수정하면서 다시 시도해볼게요!

2024-06-09 05:00 UTC, hae-on commented on Frontend/src/types/common.ts
> +export type DetailPolicyTabVariant = 'description' | 'qualification' | 'otherInfo';
얘도 걍 tab 내부 type으로 자리 옮길까요?

2024-06-09 05:20 UTC, HyeryongChoi commented on Frontend/src/components/@common/TabMenu/constants.ts
> +  { value: 'description', label: '상세내용' },
오옹 일단 해놓으면 깔끔할 것 같아여!

2024-06-09 05:21 UTC, HyeryongChoi commented on Frontend/src/types/common.ts
> +export type DetailPolicyTabVariant = 'description' | 'qualification' | 'otherInfo';
넹 좋아용

2024-06-09 06:06 UTC, hae-on commented
@HyeryongChoi 
수정 끗~~

2024-06-09 06:15 UTC, HyeryongChoi approved these changes
확인완~~

2024-06-10 01:36 UTC, merged